@startuml spolecneevidencecoajak
!include <archimate/archimate>
left to right direction
title Typizované společné evidence v úřadu
footer 
© 2022 Architektonické vzory, EGdílna.cz
github.com/egdilna/architektura-urady
end footer
Grouping(groupingspolecneevidence, "Společné evidence") {
Application_Component(es, "Evidence subjektů") 
Application_Component(edu, "Evidence digitálních úkonů") 
Application_Component(epds, "Evidence poskytování digitálních služeb") 
}
Application_DataObject(subjekteviddo, "Subjekt evidovaný v informačním systému") 
Application_DataObject(udajeodu, "Údaje o přijatém digitálním úkonu") 
Application_DataObject(osvedcenidudo, "Osvědčení o digitálním úkonu") 
Application_DataObject(udajeoposkytds, "Údaje o poskytnutí digitální služby") 
Application_DataObject(potvrzeniposkytds, "Potvrzení o poskytnuté digitální službě") 
Application_DataObject(vystupdsdo, "Výstup digitální služby") 
Application_DataObject(zaznamoosvedcenidu, "Záznam o poskytnutí osvědčení o digitálním úkonu") 
Application_DataObject(zaznamopotvrzenids, "Záznam o poskytnutí potvrzení o poskytnuté digitální službě") 
Application_DataObject(zaznamoposkytnutivystupuds, "Záznam o poskytnutí výstupu digitální služby") 

Rel_Access(es, subjekteviddo)
Rel_Access(edu, udajeodu)
Rel_Access(edu, osvedcenidudo)
Rel_Access(edu, zaznamoosvedcenidu)
Rel_Access(epds, udajeoposkytds)
Rel_Access(epds, potvrzeniposkytds)
Rel_Access(epds, vystupdsdo)
Rel_Access(epds, zaznamopotvrzenids)
Rel_Access(epds, zaznamoposkytnutivystupuds)
@enduml


@startuml eidramecproovm
!include <archimate/archimate>
left to right direction
title Požadavky a rámec pro elektronickou identifikaci u OVM
footer 
© 2022 Architektonické vzory, EGdílna.cz
github.com/egdilna/architektura-urady
end footer

Business_Role(qsep, "Kvalifikovaný poskytovatel služeb s EID") 
Business_Service(sluzbaeid, "Prokázání totožnosti s využitím elektronické identifikace") 
Application_Component(nia, "Národní bod EID (NIA)") 
Application_Component(qalsystemeid, "Kvalifikovaný systém elektronické identifikace") 
Grouping(g, "Povinné požadavky souladu") {
Motivation_Requirement(eidvsreqsouladu1, "Elektronickou identifikaci poskytuje výhradně kvalifikovaný systém") 
Motivation_Requirement(eidvsreqsouladu2, "Elektronická identifikace je poskytována prostřednictvím NIA") 
Motivation_Requirement(eidvsreqsouladu3, "Elektronická identifikace jednoznačně identifikuje osobu") 
Motivation_Requirement(eidvsreqsouladu4, "Elektronická identifikace probíhá s využitím kvalifikovaného prostředku") 
Motivation_Requirement(qseidreqsouladu1, "QSEID spravuje Kvalifikovaný správce") 
Motivation_Requirement(qseidreqsouladu2, "QSEID splňuje technické specifikace pro EID") 
Motivation_Requirement(qseidreqsouladu3, "QSEID poskytuje služby EID prostřednictvím NIA") 
Motivation_Requirement(qseidreqsouladu4, "QSEID v okamžiku identifikace ověřuje osobu") 
Motivation_Requirement(qseidreqsouladu5, "QSEID využívá jen prostředky splňující technické specifikace") 
Motivation_Requirement(eidvsreqsouladu1, "Elektronickou identifikaci poskytuje výhradně kvalifikovaný systém") 
Motivation_Requirement(eidvsreqsouladu2, "Elektronická identifikace je poskytována prostřednictvím NIA") 
}
Rel_Access(qsep, sluzbaeid)
Rel_Serving(nia, sluzbaeid)
Rel_Access(qsep, sluzbaeid)
Rel_Association(qsep, eidvsreqsouladu1)
Rel_Association(qsep, eidvsreqsouladu2)
Rel_Association(sluzbaeid, eidvsreqsouladu1)
Rel_Association(sluzbaeid, eidvsreqsouladu2)
Rel_Association(sluzbaeid, eidvsreqsouladu3)
Rel_Association(sluzbaeid, eidvsreqsouladu4)
Rel_Association(qalsystemeid, qseidreqsouladu1)
Rel_Association(qalsystemeid, qseidreqsouladu2)
Rel_Association(qalsystemeid, qseidreqsouladu3)
Rel_Association(qalsystemeid, qseidreqsouladu4)
Rel_Association(qalsystemeid, qseidreqsouladu5)
@enduml